Loftleague.com is the core product of DDM Tech Private Limited “Loftleague.com”. Loftleague.com is a cricket portal which operates cricket-based fantasy games. Any person utilizing Loftleague.com (“User”) or any of its features including participation in the various contests (“Amusement Facilities”/”Game”) being conducted on Loftleague.com shall be bound by this Privacy Policy.
Loftleague.com respects the privacy of its Users and is committed to protect it in all respects with an intention to cater to ameliorate integrated internet experience to its Users. Kindly take time to read the 'About Us' section to know more about Loftleague.com. Most of the Amusement Facilities are offered for free but you may need registration to participate in Loftleague.com's online games. The information about the User is collected by Loftleague.com as
•	(i) information supplied by Users,
•	(ii) information automatically tracked during User's navigation on Loftleague.com.
REGISTRATION :
To avail certain Amusement Facilities on our websites, Users would be required to provide certain information for the registration process namely:
•	1. Username
•	2. Password
•	3. Email address
•	4. Mobile Number
In addition to the above information, in the course of providing you with access to the Services, and in order to provide you access to the features offered through the Portal and to verify your identity, you may be required to furnish additional information, including your
Permanent Account Number,
Aadhar Card Number,
Bank Account Number,
IFSC code
These are Sensitive Personal Information (“SPI”) collected from you on the Portal. SPI means such personal information which consists of information relating to your physical, physiological and mental health condition; medical records and history; biometric information, sexual orientation and financial information, such as information regarding the payment instrument/modes used by you to make such payments, which may include cardholder name, credit/debit card number (in encrypted form) with an expiration date, banking details, wallet details, etc. This information is presented to you at the time of making a payment to enable you to complete your payment expeditiously. Except for any financial information that you choose to provide while making payment for any Services on the Portal, Loftleague does not collect any other SPI in the course of providing the Services. Any SPI collected by Loftleague shall not be disclosed to any third party without your express consent, save as otherwise set out in this Privacy Policy or as provided in a separate written agreement between Loftleague and you or as required by law. It is clarified that this condition shall not apply to publicly available information, including SPI, in relation to you on the Portal.

The above information relating to the User and the other information detailed elsewhere in this policy and collected by Loftleague.com shall collectively be referred to as 'Data'.

USER’S CONSENT AND RIGHT TO REVIEW THE DATA
By accessing Loftleague.com, you are consenting to our collecting, storing, sharing and processing of the Data as per the terms and conditions stated herein.

You may, after giving your consent to receive and process your Data and information on Loftleague.com, withdraw such consent at a subsequent stage. Any such withdrawal of consent from You shall need to be sent in writing to our grievance Officer at the details mentioned at the end of this policy. If you choose not to provide Data or subsequently withdraw your consent, we may not be able to provide you access to Loftleague.com. Withdrawing your consent will neither affect the lawfulness of any processing Loftleague.com conducted prior to your withdrawal, nor will it affect processing of your Data conducted in reliance on lawful processing grounds other than consent nor will it affect any statutory requirement on Loftleague.com to retain such Data post withdrawal of your consent.

You may unsubscribe from our marketing communications by clicking on the “unsubscribe” link located on the bottom of our e-mails, updating your communication preferences, or by sending us email to support@Loftleague.com

You shall be permitted, as and when requested by you, to review the Data which you had provided. If you find any inaccuracy or deficiency, you may ask for corrections to be made and Loftleague.com will try to accommodate your request to the extent feasible. Loftleague.com shall at no point in time be responsible for any inaccurate information provided by Users.
USER INVITATIONS :
In the course of providing the Amusement Facilities, Users may invite other existing Users or other users (“Invited Users”) to participate in any of the Amusement Facilities by providing the email address. Loftleague.com may thereafter use this information to contact the Invited User and invite such user to register with Loftleague.com (if such Invited User is not an existing User) and participate in the Game/Amusement Facility in relation to which such person was invited by the User. The participation of the Invited User in any of the Amusement Facilities shall be subject to the terms of this Privacy Policy and the Terms and Conditions for the use of the Loftleague.com website (available here). The User hereby represents that the Invited Users have consented and agreed to such disclosure to and use of their email address by Loftleague.
PURPOSE AND USAGE OF DATA :
All required information is specific and based on the kind of Game/ Amusement Facility the User wishes to participate in or access,and will be utilised for the purpose of providing services, including the Amusement Facility, requested by the User. The information as supplied by the Users enables us to improve our Amusement facilities and provide you the most user-friendly game experience.We may also share such information with affiliates and third parties in limited circumstances, including for the purpose of providing services requested by the User, complying with legal process, preventing fraud or imminent harm, and ensuring the security of our network and services.

We may also share information (such as your Loftleague.com ID) and data concerning your usage of the Amusement Facility and participation in the Games with third party service providers engaged by us, for the purpose of data analytics or other similar purposes, for the purpose of improving our services and helping us serve you better.

Where we propose to use your personal information (that is, information that that may be used to identify the User and that is not otherwise publicly available, such as the User’s or Invites User's name, email address, address and date of birth) for any other uses we will ensure that we inform you first. You will also be given the opportunity to withhold or withdraw your consent for your use other than as listed above.

Loftleague reserves the right to share, disclose and transfer information collected hereunder with its own affiliates. In the event Loftleague sells or transfers all or a portion of its business assets, consumer information may be one of the business assets that are shared, disclosed or transferred as part of the transaction. You hereby expressly grant consent and permission to Loftleague for disclosure and transfer of information to such third parties. Loftleague may share information as provided by you and data concerning usage of the services and participation in the Game with its commercial partners for the purpose of facilitating user engagement, for marketing and promotional purposes and other related purposes. Further, Loftleague reserves the right to disclose personal information as obligated by law, in response to duly authorized legal process, governmental requests and as necessary to protect the rights and interests of Loftleague.

To improve the performance & helpfulness of our game sites for our Users, we use "cookies", or such similar electronic tools to collect information to assign each visitor a unique random number as a User Identification (User ID) to understand the User's individual interests using the identified computer. Unless the User voluntarily identifies himself/herself (e.g, through registration), Loftleague.com has no way of knowing who the User is, even if we assign a cookie to the User's computer. The only personal information a cookie can contain is information supplied by the User. A cookie cannot read data off the User's hard drive. Our advertisers may also assign their own cookies to the User's browser (if the User clicks on their ad banners), a process that Loftleague.com does not control.

Loftleague.com's web servers automatically collect limited information about User's computer's connection to the Internet, including User's IP address, when the User visits our site. (User's IP address is a number that lets computers attached to the Internet know where to send data to the User -- such as the web pages viewed by the User). The User's IP address does not identify the User personally. Loftleague.com uses this information to deliver its web pages to Users upon request, to tailor its site to the interests of its users, to measure traffic within its site and let advertisers know the geographic locations from where Loftleague.com's visitors come. Loftleague.com also includes links to other websites. Such websites are governed by their respective privacy policies, which are beyond Loftleague.com's control. Once the User leaves Loftleague.com's servers (the User can tell where he/she is by checking the URL in the location bar on the User's browser), use of any information provided by the User is governed by the privacy policy of the operator of the site which the User is visiting. That policy may differ from Loftleague.com's own. If the User can't find the privacy policy of any of these sites via a link from the site's homepage, the User may contact the site directly for more information.

SECURITY MEASURES :
When Loftleague.com presents information to it's online advertisers -- to help them understand our audience and confirm the value of advertising on our website -- it is usually in the form of aggregated statistics on traffic to various pages within our site. When you register with Loftleague.com, we contact you from time to time about updating your content to provide features which we believe may benefit you. All information gathered on Loftleague.com is securely stored within Loftleague.com-controlled database. The database is stored on servers secured behind a firewall; access to such servers being password-protected and strictly limited based on need-to-know basis. However, we understand that as competent as our security measures are, no security system is impenetrable. Thus, we cannot guarantee the security of our database, nor can we guarantee that information you supply will not be intercepted while being transmitted to us over the Internet. Further, any information you include in a posting to the discussion areas will be available to anyone with Internet access.
AMENDMENT TO THE POLICY :
Loftleague.com also believes that the internet is an ever-evolving medium. We may periodically review from time to time and change our privacy policy to incorporate such future changes as may be considered appropriate. Our use of any information we gather will always be consistent with the policy under which the information was collected, regardless of what the new policy may be.
THIRD PARTY WEBSITES :
We use third-party advertisers to serve ads when you visit our websites. These advertisers may use information (excluding your name, address, email address or telephone number) about your visits to this and other websites in order to provide advertisements about goods and services which might interest you. If you would like more information about this practice and to know your choices about not having this information used by these companies, Several deceptive emails, websites, blogs etc. claiming to be from or associated with Loftleague.com may or are circulating on the Internet. These emails, websites, blogs etc. often include our logo, photos, links, content or other information from any of Loftleague.com. Some emails, websites, blogs etc. call the user to provide login name, password etc. or that the user has won a prize/ gift or provide a method to commit illegal/ unauthorised act or deed or request detailed personal information or a payment of some kind. The sources and contents of these emails, websites, blogs etc. and accompanying materials are in no way associated with the Loftleague.com. For your own protection, we strongly recommend not responding to emails or using websites, blogs etc.
Any grievance, questions or clarifications with respect to this Policy can be sent to Loftleague.com at 
Support@Loftleague.com 
Or by normal/physical mail
DDM Tech Private Limited.
Office  101, Hosabasavanapura, Medahalli, Bengaluru, Karnataka 560049


